require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '2348103561817',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'DENNIS-MD',
    ANTICALL: process.env.ANTICALL || 'off',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUQ5eVFrelpUZmpxakkxTDloR0ZkMEJsRGVCNjUvU0gzRERoaXVaQ29rbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiN1NIdG9Ubyt6bXpxaEtaTFJzWDBob2pIV2ZiVlBuaUJUTGE4Zy9mb0FuQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFSTIydVlXTEJYUi9SNkN4bVVlUUlhNVc0bmVZRkNocFNaQ2J0aXlPOUVRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVM1RXREM1Wm53MkZmUDRNVUJlY3RYeTZYZGd4cFBJUy9yS0U2VkxvM0UwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhJMWJuSWpmdWg1WW5GdVJqSDBNaS9lODJZU24rZmtGdEJZWjlUeFlUa0U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InF3SDdFdkVoRnB0QXBYQVErcSt5VnhuK0s5MmZLK1FyckkyUjNHZVVVa1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieVBUN01VcTk5TFVmZk9sZmo0RjdWWk5vQ0x0TVc5QlhrWTlqSm1CTzdXUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicWFkQlk5SjFDRUVScXh3QVJWWmRjVi9GMWs2b1BHd0pqTWFGODFwSUpHTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlhOOGRTSitTSG1rZnZzSVhVT1ZUZzg0ekh6dzNpTXV0eGh3ZTYyNDdnNld1SW05N24rSUhBU3NyN242YldxdXFUUlFmVGRORXZHaE5zcTdEY1FaOUNRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NzYsImFkdlNlY3JldEtleSI6IkFUUVlOM2xEdUMyYmVrQ0FnNmt6WUpHV1BwTTU4S2w0ck43OG5rTEExOEU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0ODEwMzU2MTgxN0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzRCNkNDQTVFMjE2Qjc1OTI5NjYzN0JFNkQ0QTk1RCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzNTUzMDA3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ4MTAzNTYxODE3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjM1QTgzMUZEMDM1NzlGMzU0OTlGRjU2QUIxNTU2QjNCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTM1NTMwMTZ9XSwibmV4dFByZUtleUlkIjo2MSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjYxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjZYQ0YyVFoyIiwibWUiOnsiaWQiOiIyMzQ4MTAzNTYxODE3OjMwQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkFyaWJvYm8gQ29tcHV0ZXJzIiwibGlkIjoiMjI4NTMwODUwMjIzMTozMEBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0t6dm9aSUZFTit3bE1RR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjVVeCtYaUhFRlBKQUE4T3p5UUJWNCtIV0hHdERzTERuVTM0WU1TZU5RMmM9IiwiYWNjb3VudFNpZ25hdHVyZSI6InFiZkNiMmJOOEJSTHRDT3lQSW9Ydi9DejhNWG15bmJsb0pxSjMzSnYrZ1V1R21LZTE2SEpUc25zcG0yeVR1eUQ5RjRBSTViSHYxMzNVK3p6ZDhTTEFRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJoRmpjVGViUFBhNW9GVmh4VUY3c3FoOFk3MmRvQlFqbXlOc2svcTZIdDZST0g2TGxrQnZTY0VLdHhOS2laZXZqd3pYbmRQWmNOYXFPR2laQ1ljZnNEZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgxMDM1NjE4MTc6MzBAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZVZNZmw0aHhCVHlRQVBEczhrQVZlUGgxaHhyUTdDdzUxTitHREVualVObiJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUzNTUzMDA1LCJsYXN0UHJvcEhhc2giOiIyUDFZaGYiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUE3eSJ9',
    timezone: 'Africa/Nigeria',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
