require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '15155097869',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUZuQ0FGN2tQUldGL0VkSjkrVFJpNk9HQVFNR04wdGYvNi8wL2EzVVUyQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUpnZXJSZmRzcExXQnpocUNDSmcxeWNJK3dET0VDSEJIVDl3U2lnYjEwbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1QUJyT1RmOTN4TzA2UVhSbEJ3cHpHaXE1ZFRXTFVxdHgya01sKzh4cmtrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpaXdpTEU0a0I4OTBJMFZDOGZ6QTFQMmUyeHRod2l5dkY3a1Z0OGxka2hZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRPOUdWZGl4SmIzb3d4ZDJnT2IvamFjR0ViTmpKOUZxOFluK1lUb2pJa289In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1YZDFuV25FbDdQKzJzSmQzRFV5Z1NIdjg3Q1hjWmY4VVFPM1JkOUJIMTg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUNjODZjdHgyZWpWaC9sQlI1NDZacTRhcGtyTEQwenY4L1FpK2hTQSswcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUN0Vi9HbTQySWhvMHEyN1lRaTRBZ2xvMWhESk9jY1dJa2FwbUdlTHF6Yz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iit4a1hGK2Vad1QzbHpIaWFUQWk5YmR0eEZXSTZ0cHFOaHg5aEtlQUVqZFJDRVd6OW9CQ1M0eHA4ZjBhWGdxcnVYN2l6aFJXYjJnWS93RE0yTTBwT2h3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzAsImFkdlNlY3JldEtleSI6InVqRHlweEpvQ0RQOUxpOHlyWXJ1Z2tJS1dxaE92Q093aG9rc1p5dXhOMjA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODAxNjY1MjNGMjREQzIxOThEMEFDMTEzMkU3MDhDOUEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc3NDkwOX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRjQxQ0JFQjkwNkVENDMwQzY0RjQxNDc2NDk2MkY3NzcifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc3NDkxMH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNUVERTc5NzRGN0U2RkY0QzlFQzIzRTUxRTkxQUJDNjMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc3NDkzM31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiRFZMQlhKNzgiLCJtZSI6eyJpZCI6IjE1MTU1MDk3ODY5OjRAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIyMDI2OTI5OTU1Nzk5NTI6NEBsaWQiLCJuYW1lIjoiSGFvIFdhbmcifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ09lbXJaRUdFTy82M3NRR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImpIaEhWRlhCNGlZN05ibXVNMGw2RG03TDNEcnJpZkJIOHpMakhmVlArekE9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkVRRUNmMEJyM3I5Vk9wdUxkZHJicWVLYXA0emhjZHIzS2xCUmVIT0t1RW1RMGttVlhBcHMxd2hseUlPN3FQRjJBYmdpSFJrNFJ0OURyR1FBWUZNdEF3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJldDhiSitzb2RJa1ZrYUxIcHVBNkZPZDdEY25LazdVTkhQZzhDWE85TktKVWpHRHQ5VHh4VkJmbnQveGhrbXdZdTM4ejEycXRsOEJjMWNVTE9PUjloZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjE1MTU1MDk3ODY5OjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWXg0UjFSVndlSW1Pelc1cmpOSmVnNXV5OXc2NjRud1IvTXk0eDMxVC9zdyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU0Nzc0OTA3LCJsYXN0UHJvcEhhc2giOiIyVjc3cVUiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUp3NCJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
