require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '15155097869',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0xtVUJCaTNzeEZvMTczTUhkYXZhQ244MGhVd2liY21yckxSUytRM2xWVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRzMzUTVXb3hCSTJLQWlkellNWFlJUFhpeUFicTlUWW1NUE5aWVNCbmZuYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDT2RSbmlQdHFQcUE3UGF5WENCSWVYZUp2QUJwc0Fpb0VLblJsZXY4M1drPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJacUd6S2N4b3hPTC9lOWhWdHZjT1F4dnJxRnFQdGpSbVhUdVBjZVpEbVYwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdQbDJWTkZVb1dDYmtNRVM2K0tJbDBYaFFkRjgwSzkxRVNmOFNUTU1KR1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InorZGtWMDMvZUZiRWV0VjZtM2c2S0wrR2NrTVVFcHBjZUtFSEQ2aVBuamc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUU5tSWVZRFc1cHVyT2hUZ2xtRnVIT2NnUjhkQSt5ZUtJczhhMG1HcHFGcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiL0tQN3RGa2FqMXhIL0N1R2tmdGpEV1dMWk5DNnBVYlEzclpld0tGNkF3OD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklwVnE2ZGRsSWU0WjBESkdEdGh3c0tDaU1pWXFQcThzTjJ0ZHpZcTVNQ3dYQVRTdXhEOWxlQmlsdzh6aWlqU0lxSnhKM2VBelRENXR6ak16RHEyRmdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODEsImFkdlNlY3JldEtleSI6IitaT0d2MHlOUXFJcGZkRzluWE5TcGFYaU9nbXRPMTM0NUNUMDRJeit4MHc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRUMxMUZFMDUzMEMzMjU1REVCMTE5NTIyNEZEM0VGM0YifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc0MDYxNX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzhCMDFGRUM5MEU1RjI5NUI2MTM1MTJDRjM4MjYzMjMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc0MDYyM30seyJrZXkiOnsicmVtb3RlSmlkIjoiMTUxNTUwOTc4NjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMkMxQ0Q5MzRGOENCNTA3MUYzMTdBODFFRTUwNEE3N0YifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDc0MDY1Mn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiSjY0TjhSMTMiLCJtZSI6eyJpZCI6IjE1MTU1MDk3ODY5OjNAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIyMDI2OTI5OTU1Nzk5NTI6M0BsaWQiLCJuYW1lIjoiSGFvIFdhbmcifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ09hbXJaRUdFUFh1M01RR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImpIaEhWRlhCNGlZN05ibXVNMGw2RG03TDNEcnJpZkJIOHpMakhmVlArekE9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImlpVTYweFZhUytPRkV0SXdyOHRMQ3U2a0lpQ25uZFZ5YklLRmdOZUNiZ3JPdmFVUUtpTkJibW9oaHRYTmN4UmZMOGd4Q0M4T1hhcFFPK1Q5Z09SMkNBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiI4M0drVTZLaE9HS29CeVRTakc5UEt1UStIU1E0dzF6ZHFyQVE1QXNvMVZ6ejAyWi9WcG5Ob3E0VkpETmNDY3pVcmxzS0ttTGxrMzFXQ0JQekZ1Y0xqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjE1MTU1MDk3ODY5OjNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWXg0UjFSVndlSW1Pelc1cmpOSmVnNXV5OXc2NjRud1IvTXk0eDMxVC9zdyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU0NzQwNjEyLCJsYXN0UHJvcEhhc2giOiIyVjc3cVUiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU4yVSJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
